### ISSUE TITLE
Reasoning

### ISSUE THREAD

**Issue by ptman** [mjl-/vex#1]
Great work! Would you like to write some reasoning for developing this? How does it compare to https://github.com/distribution/distribution ? Or https://alternativeto.net/software/docker-hub/?license=opensource ?

**Comment by mjl-** [comment]
Hi, thanks for asking!

I'm using vex to host docker images for https://github.com/mjl-/mox. A little bit more context at https://github.com/mjl-/mox/commit/a9b2bc8cec74f6590302d0329a0b0a91521d5363. In short: the docker hub announcement and preference for self-hosting. See https://r.xmox.nl/ for a public instance.

I don't use docker much myself. It doesn't help me much since I'm mostly making Go applications that can be reproducibly (cross) compiled into static binaries. Some users of mox do use docker, and I'm OK with providing docker images. But I didn't want to run a registry using docker (seems common), and I only need a minimal feature set. I hoped it would not take too much time to write something that serves a few files by digest. Comparing existing solutions and setting one up and maintaining it also takes time, and is certainly less fun. And I now know more about docker images and registries...

Vex is probably much more minimal than popular alternatives. Some examples:

- Very basic authorization mechanism: any authenticated user has full control over all repositories. Good enough if the images in a registry are maintained by a small organization or small set of people. No teams and user groups etc.
- Not very configurable or pluggable. E.g. storage is always in the local file system, along with a builtin database. Good enough for small-scale use.

Looking at https://github.com/distribution/distribution, it appears to have a reference implementation and a library. Is this the "go to" registry software for folks hosting their own registries? I'm probably overlooking the instructions to set it up...

From https://alternativeto.net/software/docker-hub/?license=opensource: gitlab (a huge application), harbor (uses: postgresql, redis, and 6 more components, so also big), a "dedicated container registry" that claims to be both no-frills and based on harbor, and potus that is an authorization service for a registry (?). These likely do much more than vex.

As said, I'm not really into the docker ecosystem. There is probably registry software out there that fits my needs. And I may have missed something important about registries (new manifest types? signatures?). I went by the registry specification on the docker website, but I'm now thinking I should have found the OCI spec sooner and use that. I'm open to suggestions. (:

**Comment by ptman** [comment]
Thank you for taking the time to answer. This would be great content for the README. Docker distribution is quite easy to setup and also has low requirements, but the repository doesn't have all documentation. https://docs.docker.com/registry/deploying/

**Comment by mjl-** [comment]
Good point, I moved the documentation to the README, that's more helpful.

I had seen the registry page at the docker website before. I probably dismissed it (too easily) because it has all the instructions for running with docker. Perhaps that should be the tag line for vex: docker registry for non-docker users...

Thanks for the discussion. Feel free to reopen if there is more to discuss.
